arch:
  - amd64
  - ppc64le
language: java
jdk:
- openjdk11
- openjdk12
- openjdk13
- openjdk14

install: skip

before_script:
  # execute all of the commands which need to be executed 
  # before running actual tests  
  - if [ "$TRAVIS_ARCH" = "ppc64le" ]; then mkdir -p /opt/maven; sudo apt-get update; sudo apt-get install maven;export MAVEN_HOME=/opt/maven; export PATH=${MAVEN_HOME}/bin:${PATH};  fi
  - printenv
  - ls -R -d /usr/lib/jvm/*
  - sed -i "s|JDK_home|$JAVA_HOME|g" ci-toolchains.xml
script:
  # execute all of the commands which 
  # should make the build pass or fail
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -t ci-toolchains.xml